---

apiVersion: v1
kind: Pod
metadata:
  name: master
  namespace: dev
spec:
  containers:
  - name: master
    image: saikrishnaoduru/jmeter:latest
    args: ["-n -t /jmeter/First.jmx -l /jmeter/results/result-2023-02-08_17-41-36.jtl -j /jmeter/logs/master-log-2023-02-08_17-41-36.log  -e -o /jmeter/HtmlReport-2023-02-08_17-41-36 -R slave1; while true; do sleep 30; done;"]
    env:
    - name: JVM_ARGS
      value: "-Xms512m -Xmx1024m"
    - name: mode
      value: "master"
    resources:
      limits:
        memory: 1024Mi
        cpu: 1000m
      requests:
        cpu: 1000m
        memory: 1024Mi

---

apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  selector:
    app: master
  ports:
    - name: master
      port: 1099
  type: ClusterIP

---
