---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slave2
spec:   
  selector:
    matchLabels:
      app: slave2
  serviceName: slave2
  replicas: 1
  template:
    metadata:
      labels:
        app: slave2
    spec:
      containers:
      - name: slave2
        image: saikrishnaoduru/jmeter:latest
        args: ["-n -t /mnt/jmeter/script.jmx -l /mnt/jmeter/results/result-2023-02-08_17-41-36.jtl -j /mnt/jmeter/logs/slave2-log-2023-02-08_17-41-36.log -R SERVERS"]
        env:
        - name: JVM_ARGS
          value: "-Xms512m -Xmx1024m"
        - name: mode
          value: "slave2"
        resources:
          limits:
            memory: 1024Mi
            cpu: 1000m
          requests:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
          - name: slave2
            mountPath: /mnt/jmeter
      volumes:
      - name: slave2
        hostPath:
          path: /home/saikrishna/Downloads/jmeter/kubernetes-init/data/
          type: DirectoryOrCreate 
---

apiVersion: v1
kind: Service
metadata:
  name: slave2
spec:
  selector:
    app: slave2
  ports:
    - name: slave2
      port: 1099
  type: ClusterIP

---
