---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slave1
  namespace: dev
spec:   
  selector:
    matchLabels:
      app: slave1
  serviceName: slave1
  replicas: 1
  template:
    metadata:
      labels:
        app: slave1
    spec:
      containers:
      - name: slave1
        image: saikrishnaoduru/jmeter:latest
        args: ["-n -t First.jmx -l /results/result.jtl -j /logs/slave1-log.log -R SERVERS; while true; do sleep 80; done;"]
        env:
        - name: JVM_ARGS
          value: "-Xms512m -Xmx1024m"
        - name: mode
          value: "slave1"
        resources:
          limits:
            memory: 1024Mi
            cpu: 1000m
          requests:
            cpu: 1000m
            memory: 1024Mi
       
---

apiVersion: v1
kind: Service
metadata:
  name: slave1
spec:
  selector:
    app: slave1
  ports:
    - name: slave1
      port: 1099
  type: ClusterIP

---
