apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: mybinding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role
  namespace: dev
subjects:
- kind: ServiceAccount
  name: myaccount
  namespace: dev
  apiGroup: rbac.authorization.k8s.io
